export const USER_LOGGED_IN = 'USER_LOGGED_IN'
export const USER_LOGGING_IN = 'USER_LOGGING_IN'
export const USER_LOGGED_OUT = 'USER_LOGGED_OUT'
export const USER_FAILED_TO_LOGIN = 'USER_FAILED_TO_LOGIN'

export const USER_REGISTERING = 'USER_REGISTERING'
export const USER_REGISTERED = 'USER_REGISTERED'
export const USER_FAILED_TO_REGISTER = 'USER_FAILED_TO_REGISTER'

export const DASHBOARD_FETCHING = 'DASHBOARD_FETCHING'
export const DASHBOARD_FETCHED = 'DASHBOARD_FETCHED'
export const DASHBOARD_FETCHING_FAILED = 'DASHBOARD_FETCHING_FAILED'

export const ANIME_FETCHING = 'ANIME_FETCHING'
export const ANIME_FETCHED = 'ANIME_FETCHED'
export const ANIME_FETCHING_FAILED = 'ANIME_FETCHING_FAILED'